"""Phase 2 wCV between-substitution comparison (Amendment 6 sec 6b -- SA-28).

Consumes two wCV parquets produced by `scripts/run_phase2_poisson_reference.py`
(autopet_iii_primary and autopet_i_sensitivity) and applies the pre-registered
sec 3.5 "Validation of fallback" comparison: two-sample Kolmogorov-Smirnov test
plus Bland-Altman analysis, per dose level, per SUV statistic.

The comparison was originally specified for real-vs-synthetic wCV but is
re-targeted as between-substitution per Amendment 6 sec 6b (real serial pairs
unavailable; combined-cohort sec 3.5 enumeration verdict 0 in-window pairs).

Pre-specified disagreement criteria (Amendment 6 sec 6b):
    KS p < 0.05  OR  |Bland-Altman bias| > 10 pp  OR  LoA span > 20 pp
        -> manuscript caveat: AutoPET-I sensitivity-check wCV NOT interchangeable
           with the primary reference.

Outputs:
    {OUT_PREFIX}_comparison.csv  -- one row per (dose_fraction, suv_statistic)
                                     with KS stat / KS p / mean_bias / loa_low / loa_high / verdict
    {OUT_PREFIX}_comparison.md   -- narrative summary referencing Amendment 6 sec 6b

Pre-registration: https://doi.org/10.17605/OSF.IO/4KAZN sec 3.5
Amendment 6: 2026-04-29 (SA-28 added to sec 5.5)
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

REPO_ROOT = Path(__file__).resolve().parents[1]

# Amendment 6 sec 6b pre-specified disagreement thresholds
KS_ALPHA = 0.05
BIAS_THRESHOLD_PP = 10.0
LOA_SPAN_THRESHOLD_PP = 20.0

SUV_STATS = ("suvmax", "suvpeak", "suvmean")


def _bland_altman(x: np.ndarray, y: np.ndarray) -> dict:
    """Bland-Altman bias + 95% limits-of-agreement on two unmatched samples.

    Because the two cohorts are not patient-matched, this is the *unmatched*
    Bland-Altman variant: bias = mean(x) - mean(y); LoA derived from the
    SD of the per-cohort mean-pair differences using a pooled-SD assumption.
    For unmatched data this is approximate; the more rigorous comparison is
    the KS test (which is reported alongside).
    """
    bias = float(np.mean(x) - np.mean(y))
    pooled_sd = float(np.sqrt((np.var(x, ddof=1) + np.var(y, ddof=1)) / 2.0))
    loa_low = bias - 1.96 * pooled_sd
    loa_high = bias + 1.96 * pooled_sd
    return {
        "bias_pp": bias,
        "loa_low_pp": loa_low,
        "loa_high_pp": loa_high,
        "loa_span_pp": loa_high - loa_low,
        "pooled_sd_pp": pooled_sd,
    }


def _per_combination_comparison(
    primary: pd.DataFrame,
    sensitivity: pd.DataFrame,
    dose_fraction: float,
    suv_stat: str,
) -> dict:
    col = f"wcv_{suv_stat}_pct"
    p = primary.loc[primary["dose_fraction"] == dose_fraction, col].dropna().to_numpy()
    s = sensitivity.loc[sensitivity["dose_fraction"] == dose_fraction, col].dropna().to_numpy()
    if len(p) < 5 or len(s) < 5:
        return {
            "dose_fraction": dose_fraction, "suv_stat": suv_stat,
            "n_primary": len(p), "n_sensitivity": len(s),
            "ks_stat": float("nan"), "ks_pvalue": float("nan"),
            "primary_median": float("nan"), "sensitivity_median": float("nan"),
            "bias_pp": float("nan"), "loa_low_pp": float("nan"),
            "loa_high_pp": float("nan"), "loa_span_pp": float("nan"),
            "verdict": "INSUFFICIENT_DATA",
        }
    ks = stats.ks_2samp(p, s)
    ba = _bland_altman(p, s)
    fail_ks = ks.pvalue < KS_ALPHA
    fail_bias = abs(ba["bias_pp"]) > BIAS_THRESHOLD_PP
    fail_loa = ba["loa_span_pp"] > LOA_SPAN_THRESHOLD_PP
    if fail_ks or fail_bias or fail_loa:
        verdict = "DISAGREE"
    else:
        verdict = "AGREE"
    return {
        "dose_fraction": dose_fraction, "suv_stat": suv_stat,
        "n_primary": int(len(p)), "n_sensitivity": int(len(s)),
        "primary_median": float(np.median(p)), "sensitivity_median": float(np.median(s)),
        "primary_iqr_low": float(np.percentile(p, 25)), "primary_iqr_high": float(np.percentile(p, 75)),
        "sensitivity_iqr_low": float(np.percentile(s, 25)), "sensitivity_iqr_high": float(np.percentile(s, 75)),
        "ks_stat": float(ks.statistic), "ks_pvalue": float(ks.pvalue),
        "ks_alpha": KS_ALPHA,
        "bias_pp": ba["bias_pp"], "bias_threshold_pp": BIAS_THRESHOLD_PP,
        "loa_low_pp": ba["loa_low_pp"], "loa_high_pp": ba["loa_high_pp"],
        "loa_span_pp": ba["loa_span_pp"], "loa_span_threshold_pp": LOA_SPAN_THRESHOLD_PP,
        "fail_ks": fail_ks, "fail_bias": fail_bias, "fail_loa": fail_loa,
        "verdict": verdict,
    }


def write_markdown_report(rows: list[dict], path: Path) -> None:
    lines = [
        "# Phase 2 wCV Between-Substitution Comparison Report",
        "",
        "Generated by `scripts/run_phase2_validation.py`. Implements Amendment 6 §6b "
        "(SA-28: re-targeted §3.5 'Validation of fallback' clause as between-substitution "
        "comparison since real serial pairs unavailable).",
        "",
        "**Pre-specified disagreement criteria (Amendment 6 §6b):**",
        f"- Two-sample Kolmogorov-Smirnov: p < {KS_ALPHA}",
        f"- Bland-Altman: |mean bias| > {BIAS_THRESHOLD_PP:.0f} percentage points",
        f"- Bland-Altman: 95% LoA span > {LOA_SPAN_THRESHOLD_PP:.0f} percentage points",
        "",
        "If ANY criterion fails -> verdict DISAGREE -> manuscript caveat: AutoPET-I "
        "sensitivity-check wCV NOT interchangeable with the primary reference.",
        "",
        "## Results table",
        "",
        "| dose | stat | n_p | n_s | median_p | median_s | KS stat | KS p | bias (pp) | LoA span (pp) | verdict |",
        "|------|------|-----|-----|----------|----------|---------|------|-----------|---------------|---------|",
    ]
    for r in rows:
        lines.append(
            f"| {r['dose_fraction']:.2f} | {r['suv_stat']} | "
            f"{r['n_primary']} | {r['n_sensitivity']} | "
            f"{r.get('primary_median', float('nan')):.2f} | {r.get('sensitivity_median', float('nan')):.2f} | "
            f"{r['ks_stat']:.3f} | {r['ks_pvalue']:.4f} | "
            f"{r.get('bias_pp', float('nan')):.2f} | {r.get('loa_span_pp', float('nan')):.2f} | "
            f"**{r['verdict']}** |"
        )
    lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    disagree = [r for r in rows if r["verdict"] == "DISAGREE"]
    insufficient = [r for r in rows if r["verdict"] == "INSUFFICIENT_DATA"]
    if disagree:
        lines.append(
            f"**{len(disagree)} of {len(rows)} (dose, statistic) combinations show DISAGREEMENT** "
            "between the AutoPET-III DICOM-grounded primary reference and the AutoPET-I "
            "literature-default sensitivity check. Per Amendment 6 §6b, this triggers an "
            "explicit manuscript caveat: the AutoPET-I sensitivity-check wCV is not "
            "interchangeable with the primary reference. The primary reference (AutoPET-III, "
            "DICOM-grounded) remains the load-bearing input to Phase 3 conformal calibration."
        )
    elif insufficient:
        lines.append(
            f"**{len(insufficient)} of {len(rows)} (dose, statistic) combinations had insufficient "
            "data (<5 lesions per cohort).** Cannot compute KS / Bland-Altman; report as a limitation."
        )
    else:
        lines.append(
            "All (dose, statistic) combinations show agreement under the pre-specified "
            "Amendment 6 §6b criteria. The AutoPET-I sensitivity-check wCV distribution "
            "is not statistically distinguishable from the AutoPET-III DICOM-grounded primary "
            "reference at the pre-specified thresholds. This strengthens the external validity "
            "of the noise model used in Phase 3 conformal calibration."
        )
    path.write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--primary-wcv", type=Path, required=True,
                    help="wCV parquet from autopet_iii_primary mode")
    ap.add_argument("--sensitivity-wcv", type=Path, required=True,
                    help="wCV parquet from autopet_i_sensitivity mode")
    ap.add_argument("--out-prefix", type=Path, required=True,
                    help="Output prefix; produces {prefix}_comparison.csv and .md")
    args = ap.parse_args()

    primary = pd.read_parquet(args.primary_wcv)
    sensitivity = pd.read_parquet(args.sensitivity_wcv)

    primary_doses = set(primary["dose_fraction"].unique())
    sensitivity_doses = set(sensitivity["dose_fraction"].unique())
    shared_doses = sorted(primary_doses & sensitivity_doses)
    if not shared_doses:
        raise RuntimeError(
            f"No shared dose fractions between primary {primary_doses} and sensitivity {sensitivity_doses}."
        )

    rows = []
    for dose in shared_doses:
        for stat in SUV_STATS:
            rows.append(_per_combination_comparison(primary, sensitivity, dose, stat))

    out_csv = args.out_prefix.with_name(args.out_prefix.name + "_comparison.csv")
    out_md = args.out_prefix.with_name(args.out_prefix.name + "_comparison.md")
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_csv(out_csv, index=False)
    write_markdown_report(rows, out_md)

    print("=== Phase 2 wCV between-substitution comparison (SA-28) ===")
    print(f"Primary cohort:     n_lesion-doses = {len(primary)} (cases = {primary['case_id'].nunique()})")
    print(f"Sensitivity cohort: n_lesion-doses = {len(sensitivity)} (cases = {sensitivity['case_id'].nunique()})")
    print(f"Shared dose fractions: {shared_doses}")
    print()
    df = pd.DataFrame(rows)
    print(df[["dose_fraction", "suv_stat", "n_primary", "n_sensitivity",
              "ks_pvalue", "bias_pp", "loa_span_pp", "verdict"]].to_string(index=False))
    print()
    print(f"Wrote {out_csv}")
    print(f"Wrote {out_md}")


if __name__ == "__main__":
    main()
